markeetplace_server/marketplace_server/urls.py
from django.contrib import admin
from django.urls import include, path

from marketplace_server import settings
from django.conf.urls.static import static

from src.apps.core.admin import admin_site

urlpatterns = [
    path('admin/', admin_site.urls ),
    path('', include('src.apps.core.urls')),
    path('vendor/', include('src.apps.vendor.urls')),
    path('product/', include('src.apps.product.urls')),
    path('accounts/',include('src.apps.accounts.urls')),
    path('cart/', include('src.apps.cart.urls')),
    path('order/', include('src.apps.order.urls')),
    # path('',include('src.apps.website.urls',namespace='website')),
    path('admin/', admin.site.urls),
    path('api/',include('src.apis.urls',namespace='api')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

markeetplace_server/src/apps/product/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

from .views import PlaceOrderView, UserOrderListView, CancelOrderView, RemoveFromWishlistView

app_name = 'product'
urlpatterns = [

    path('search', views.ProductSearchView.as_view(), name="search"),

                  # Category
    # path('categories/', views.CategoryListView.as_view(), name='category-list'),
    # path('category/create/', views.CategoryCreateView.as_view(), name='category-create'),
    # path('category/update/<int:pk>/', views.CategoryUpdateView.as_view(), name='category-update'),
    # path('category/delete/<int:pk>/', views.CategoryDeleteView.as_view(), name='category-delete'),
    #
    # # SubCategory
    # path('subcategories/', views.SubCategoryListView.as_view(), name='subcategory-list'),
    # path('subcategory/create/', views.SubCategoryCreateView.as_view(), name='subcategory-create'),
    # path('subcategory/update/<int:pk>/', views.SubCategoryUpdateView.as_view(), name='subcategory-update'),
    # path('subcategory/delete/<int:pk>/', views.SubCategoryDeleteView.as_view(), name='subcategory-delete'),
    #
    # # Product
    path('', views.ProductListView.as_view(), name='product-list'),
    path('all/', views.AllProductsView.as_view(), name='all-product'),
    path('wish_list/', views.WishListProductsView.as_view(), name='wish-list'),
    path('wishListCreate/<int:id>/', views.WishListProductsCreateView.as_view(), name='wish-list-create'),
    path('category_product/<int:id>/', views.CategoryProductsView.as_view(), name='category-product'),
    path('product_create/', views.ProductCreateView.as_view(), name='product-create'),
    path('product_detail/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('product_detail3d/<int:pk>/', views.ProductDetail3DView.as_view(), name='product-detail3d'),
    path('product_update/<int:pk>/', views.ProductUpdateView.as_view(), name='product-update'),
    path('product_delete/<int:pk>/', views.ProductDeleteView.as_view(), name='product-delete'),
    path('addToCart/<int:id>/<int:quantity>/', views.AddToCartView.as_view(), name='addToCart'),
    path('place_order/', PlaceOrderView.as_view(), name='place_order'),
    path('my-orders/', UserOrderListView.as_view(), name='user_order_list'),
    path('cancel-order/<int:order_id>/', CancelOrderView.as_view(), name='cancel_order'),
                  # NEW URLS
    path('remove-from-wishlist/<int:product_id>/', RemoveFromWishlistView.as_view(),
                       name='remove_from_wishlist'),

    path ('add_product/',views.CreateProduct.as_view(),name="addproduct"),
    path('add_product/getcategories/<str:category>/',views.GetSubCategory.as_view(),name='subcategories')
    # Media (Product media upload)
    # path('media/upload/', views.MediaCreateView.as_view(), name='media-upload'),
    # path('media/delete/<int:pk>/', views.MediaDeleteView.as_view(), name='media-delete'),

    # Shipping Info
    # path('shipping-info/create/', views.ShippingInfoCreateView.as_view(), name='shipping-info-create'),
    # path('shipping-info/update/<int:pk>/', views.ShippingInfoUpdateView.as_view(), name='shipping-info-update'),

    # Review
    # path('reviews/', views.ReviewListView.as_view(), name='review-list'),
    # path('review/create/', views.ReviewCreateView.as_view(), name='review-create'),
    # path('review/delete/<int:pk>/', views.ReviewDeleteView.as_view(), name='review-delete'),

    # Tags (For product tags)
    # path('tags/', views.TagListView.as_view(), name='tag-list'),
    # path('tag/create/', views.TagCreateView.as_view(), name='tag-create'),

    # Product Variants
    # path('product-variants/', views.ProductVariantListView.as_view(), name='product-variant-list'),
    # path('product-variant/create/', views.ProductVariantCreateView.as_view(), name='product-variant-create'),
    # path('product-variant/update/<int:pk>/', views.ProductVariantUpdateView.as_view(), name='product-variant-update'),
    # path('product-variant/delete/<int:pk>/', views.ProductVariantDeleteView.as_view(), name='product-variant-delete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

markeetplace_server/templates/hero/feature_section.html
    <div class="mt-6 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4 md:gap-8 mx-auto w-full md:w-[1250px] items-center p-3 border border-[#E4E7E9]">
      <div class="flex gap-2 items-center border-b md:border-b-0 md:border-r border-gray-300 pb-4 md:pb-0 md:pr-4">
        <span class="text-xl">✔</span>
        <div class="flex flex-col">
          <h6 class="text-[14px] font-[500]">Fastest Delivery</h6>
          <p>Delivery in 24/H</p>
        </div>
      </div>
      <div class="flex gap-2 items-center border-b md:border-b-0 md:border-r border-gray-300 pb-4 md:pb-0 md:pr-4">
        <span class="text-xl">🏆</span>
        <div class="flex flex-col">
          <h6 class="text-[14px] md:text-[16px]">24 HOURS RETURN</h6>
          <p>100% money-back guarantee</p>
        </div>
      </div>
      <div class="flex gap-2 items-center border-b md:border-b-0 md:border-r border-gray-300 pb-4 md:pb-0 md:pr-4">
        <span class="text-xl">💳</span>
        <div class="flex flex-col">
          <h6 class="text-[14px] md:text-[16px]">SECURE PAYMENT</h6>
          <p>Your money is safe</p>
        </div>
      </div>
      <div class="flex gap-2 items-center">
        <span class="text-xl">🎧</span>
        <div class="flex flex-col">
          <h6 class="text-[14px] md:text-[16px]">SUPPORT 24/7</h6>
          <p>Live contact/message</p>
        </div>
      </div>
    </div>

markeetplace_server/templates/hero/hero.html
  <div class="mt-4 grid grid-cols-1 md:grid-cols-12 gap-6 mx-auto px-4 lg:px-10">
    <!-- Main Banner -->
      {% if top_sale %}
      	      {% include 'hero/main_banner.html' %}

      {% endif %}
    <!-- Side Banners -->
{#      {% include 'hero/side_banner.html' %}#}

    <!-- Features Section -->
       {% include 'hero/feature_section.html' %}

  </div>

markeetplace_server/templates/hero/main_banner.html
{% load static %}

{% if top_sale %}
	

<div class="md:col-span-8 bg-[#F2F4F5] flex flex-col md:flex-row items-center justify-between relative p-6 md:p-8 rounded-md">
      <!-- Banner Text -->
      <div class="flex flex-col gap-4 md:gap-6 w-full md:w-[356px]">
        <div class="flex gap-1 items-center">
          <div class="h-[1px] w-[25px] border-[2px] border-[#2DA5F3] mx-2 md:mx-4"></div>
          <p class="text-[12px] md:text-[14px] font-[600] text-[#24B4C2]">THE BEST SALE ITEM</p>
        </div>
        <h1 class="text-[32px] md:text-[48px] font-[600]">{{ top_sale.name }}</h1>
        <p class="text-[16px] md:text-[18px]">
            {{ top_sale.description }}
        </p>
        <a href="{% url 'product:product-detail' top_sale.id %}" class="bg-[#073741] text-white font-[700] w-[120px] md:w-[150px] h-[50px] md:h-[70px] py-2 md:py-3 flex items-center justify-center">
          <span>Shop Now</span>
          <span class="ml-2 text-xl">→</span>
        </a>
      </div>
      <!-- Banner Image -->
      <div class="mt-6 md:mt-0 md:ml-6 w-full md:w-auto">
        <img src="{{ top_sale.media.first.file.url }}" alt="Xbox Console" class="w-full h-auto" />
      </div>
      <!-- Price Badge -->
      <div class="absolute md:top-4 top-1 md:right-4 right-1 bg-[#2DA5F3] rounded-full w-[60px] md:w-[101px] h-[60px] md:h-[101px] flex items-center justify-center text-white font-[700]">
        <span class="text-[18px] md:text-[22px]">${{ top_sale.price }}</span>
      </div>
    </div>
{% endif %}

markeetplace_server/templates/hero/side_banner.html
   <div class="md:col-span-4 flex flex-col gap-4">
      <!-- Sale Banner -->
       {% if top_sale2 %}


      <div class="bg-black flex flex-col md:flex-row h-auto md:h-[280px] rounded-md p-4 md:p-0">
        <div class="flex flex-col justify-center w-full md:w-[200px] px-4 md:px-[20px]">
          <p class="text-[#EBC80C] text-[12px] md:text-[14px]">MORE DISCOUNT</p>
          <h4 class="text-white text-[20px] md:text-[24px]">{{ top_sale2.name }}</h4>
          <a href="{% url 'product:product-detail' top_sale2.id %}" class="bg-[#FA8232] text-white font-[700] w-[120px] md:w-[150px] h-[40px] md:h-[50px] py-2 flex items-center justify-center">
            <span>Shop Now</span>
            <span class="ml-2 text-lg md:text-xl">→</span>
          </a>
        </div>
        <div class="relative flex justify-center mt-4 md:mt-0">
          <img src="{{ top_sale2.media.first.file.url }}" alt="" class="w-full h-auto" />
          <p class="bg-[#EFD33D] text-[12px] md:text-[16px] p-2 absolute top-[60px] md:top-[90px] left-1/2 transform -translate-x-1/2 whitespace-nowrap">
              {{ top_sale2.discount_price }}% OFF
          </p>
        </div>
      </div>
    {% endif %}

      <!-- Product Banner -->
{% if top_sale3 %}


      <div class="bg-[#F2F4F5] flex flex-col md:flex-row h-auto md:h-[280px] rounded-md p-4 md:p-0">
        <div class="flex items-center justify-center w-full md:w-auto">
          <img src="{{ top_sale3.media.first.file.url }}" alt="" class="w-full md:w-auto" />
        </div>
        <div class="flex flex-col justify-center px-4 md:px-4 mt-4 md:mt-0">
          <h4 class="text-black font-[600] text-[20px] md:text-[24px]">{{ top_sale3.name }}</h4>
          <p class="text-[#2DA5F3] text-[16px] md:text-[18px]">${{ top_sale3.price }}</p>
          <a href="{% url 'product:product-detail' top_sale3.id %}" class="bg-[#FA8232] text-white font-[700] w-[120px] md:w-[150px] h-[40px] md:h-[50px] py-2 flex items-center justify-center">
            <span>Shop Now</span>
            <span class="ml-2 text-lg md:text-xl">→</span>
          </a>
        </div>
      </div>
    </div>
{% endif %}