markeetplace_server/marketplace_server/urls.py
from django.contrib import admin
from django.urls import include, path

from marketplace_server import settings
from django.conf.urls.static import static

from src.apps.core.admin import admin_site

urlpatterns = [
    path('admin/', admin_site.urls ),
    path('', include('src.apps.core.urls')),
    path('vendor/', include('src.apps.vendor.urls')),
    path('product/', include('src.apps.product.urls')),
    path('accounts/',include('src.apps.accounts.urls')),
    path('cart/', include('src.apps.cart.urls')),
    path('order/', include('src.apps.order.urls')),
    # path('',include('src.apps.website.urls',namespace='website')),
    path('admin/', admin.site.urls),
    path('api/',include('src.apis.urls',namespace='api')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

markeetplace_server/src/apis/accounts/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from src.apis.accounts.views import CustomUserViewSet, LoginView, LogoutView

app_name = 'accounts'
router = DefaultRouter()
router.register(r'users', CustomUserViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

markeetplace_server/src/apps/cart/urls.py
from django.urls import path
from . import views



app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name="cart"),
    # path('success/', views.success, name="success"),
]

markeetplace_server/src/apps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'


urlpatterns = [
    path('', views.FrontPageView.as_view(), name="home"),
    path('contact-us/', views.contactpage, name="contact"),
]

markeetplace_server/src/apps/product/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

from .views import PlaceOrderView, UserOrderListView, CancelOrderView, RemoveFromWishlistView

app_name = 'product'
urlpatterns = [

    path('search', views.ProductSearchView.as_view(), name="search"),

                  # Category
    # path('categories/', views.CategoryListView.as_view(), name='category-list'),
    # path('category/create/', views.CategoryCreateView.as_view(), name='category-create'),
    # path('category/update/<int:pk>/', views.CategoryUpdateView.as_view(), name='category-update'),
    # path('category/delete/<int:pk>/', views.CategoryDeleteView.as_view(), name='category-delete'),
    #
    # # SubCategory
    # path('subcategories/', views.SubCategoryListView.as_view(), name='subcategory-list'),
    # path('subcategory/create/', views.SubCategoryCreateView.as_view(), name='subcategory-create'),
    # path('subcategory/update/<int:pk>/', views.SubCategoryUpdateView.as_view(), name='subcategory-update'),
    # path('subcategory/delete/<int:pk>/', views.SubCategoryDeleteView.as_view(), name='subcategory-delete'),
    #
    # # Product
    path('', views.ProductListView.as_view(), name='product-list'),
    path('all/', views.AllProductsView.as_view(), name='all-product'),
    path('wish_list/', views.WishListProductsView.as_view(), name='wish-list'),
    path('wishListCreate/<int:id>/', views.WishListProductsCreateView.as_view(), name='wish-list-create'),
    path('category_product/<int:id>/', views.CategoryProductsView.as_view(), name='category-product'),
    path('product_create/', views.ProductCreateView.as_view(), name='product-create'),
    path('product_detail/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('product_detail3d/<int:pk>/', views.ProductDetail3DView.as_view(), name='product-detail3d'),
    path('product_update/<int:pk>/', views.ProductUpdateView.as_view(), name='product-update'),
    path('product_delete/<int:pk>/', views.ProductDeleteView.as_view(), name='product-delete'),
    path('addToCart/<int:id>/<int:quantity>/', views.AddToCartView.as_view(), name='addToCart'),
    path('place_order/', PlaceOrderView.as_view(), name='place_order'),
    path('my-orders/', UserOrderListView.as_view(), name='user_order_list'),
    path('cancel-order/<int:order_id>/', CancelOrderView.as_view(), name='cancel_order'),
                  # NEW URLS
    path('remove-from-wishlist/<int:product_id>/', RemoveFromWishlistView.as_view(),
                       name='remove_from_wishlist'),

    path ('add_product/',views.CreateProduct.as_view(),name="addproduct"),
    path('add_product/getcategories/<str:category>/',views.GetSubCategory.as_view(),name='subcategories')
    # Media (Product media upload)
    # path('media/upload/', views.MediaCreateView.as_view(), name='media-upload'),
    # path('media/delete/<int:pk>/', views.MediaDeleteView.as_view(), name='media-delete'),

    # Shipping Info
    # path('shipping-info/create/', views.ShippingInfoCreateView.as_view(), name='shipping-info-create'),
    # path('shipping-info/update/<int:pk>/', views.ShippingInfoUpdateView.as_view(), name='shipping-info-update'),

    # Review
    # path('reviews/', views.ReviewListView.as_view(), name='review-list'),
    # path('review/create/', views.ReviewCreateView.as_view(), name='review-create'),
    # path('review/delete/<int:pk>/', views.ReviewDeleteView.as_view(), name='review-delete'),

    # Tags (For product tags)
    # path('tags/', views.TagListView.as_view(), name='tag-list'),
    # path('tag/create/', views.TagCreateView.as_view(), name='tag-create'),

    # Product Variants
    # path('product-variants/', views.ProductVariantListView.as_view(), name='product-variant-list'),
    # path('product-variant/create/', views.ProductVariantCreateView.as_view(), name='product-variant-create'),
    # path('product-variant/update/<int:pk>/', views.ProductVariantUpdateView.as_view(), name='product-variant-update'),
    # path('product-variant/delete/<int:pk>/', views.ProductVariantDeleteView.as_view(), name='product-variant-delete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

markeetplace_server/templates/header/header.html
<div>

  <!-- Black Friday Banner -->
{#  {% include "header/header_ads.html" %}#}



  <!-- Social Media Section -->
 {% include "header/social_media_section.html" %}
  <hr class="border-gray-400" />



  <!-- Main Navbar -->
{% include "header/navbar.html" %}





{#SCRIPT#}


{% include 'header/script.html' %}

</div>

markeetplace_server/templates/header/header_ads.html
<div id="black-friday-banner" class="bg-black flex flex-col sm:flex-row justify-between items-center p-2">
    <div class="flex gap-2 items-center px-4 sm:px-16">
      <p class="bg-yellow-400 text-lg sm:text-2xl px-4 py-2 transform rotate-2">Black</p>
      <p class="text-white text-lg sm:text-xl">Friday</p>
    </div>
    <div class="flex items-center gap-2 mt-2 sm:mt-0">
      <p class="text-sm text-white">Up to</p>
      <span class="text-yellow-400 text-3xl sm:text-4xl">59%</span>
      <p class="text-base sm:text-lg text-white">OFF</p>
    </div>
    <div class="flex items-center gap-2 mt-2 sm:mt-0">
    <button class="bg-yellow-400 font-bold px-4 sm:px-6 py-2 flex items-center gap-2 mt-2 sm:mt-0">
      Shop Now
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 sm:h-6 sm:w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
      </svg>
    </button>
    <button class="bg-[#073741] p-2 mt-2 sm:mt-0" onclick="document.getElementById('black-friday-banner').remove();">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 sm:h-5 sm:w-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>
    </button>
  </div>
  </div>

markeetplace_server/templates/header/navbar.html
{% load static %}
<nav class="bg-[#073741] p-4 px-4 sm:px-24 flex items-center justify-between">
    <a href="/"><img src="{% static 'Logo.png' %}" alt="Logo" class="h-10 sm:h-16"></a>
    <div id="nav-links" class="hidden sm:flex items-center gap-4">
        <form action="{% url 'product:search' %}" method="GET" class="relative mb-3">
            <input type="text" name="q" class="pl-4 pr-10 py-2 border border-gray-300 rounded w-40 sm:w-64 focus:outline-none focus:ring-2 focus:ring-blue-500" placeholder="Search for products" required>
            <button type="submit" class="absolute top-2 right-2">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-4.35-4.35M11 19a8 8 0 110-16 8 8 0 010 16z" />
                </svg>
            </button>
        </form>

        <div class="flex items-center justify-center gap-4 text-white">
            <a href="{% url 'cart:cart' %}"> <i class="fa fa-shopping-cart"></i>{% if cart %}({{cart|length}}){% endif %}</a>
            <a href="{% url 'product:wish-list' %}"><i class="fa fa-heart"></i> </a>
            {% if request.user.vendor %}
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link is-capitalized">
                        <i class="fa fa-user"></i>
                        {{ request.user.vendor.name }}
                    </a>
                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="#">
                            {{ request.user.vendor }}
                        </a>
                        <a class="navbar-item" href="{% url 'product:user_order_list' %}">
                           My Orders
                        </a>
                        <a class="navbar-item" href="{% url 'core:home' %}">
                            List Product
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="{% url 'accounts:logout' %}">
                            Logout
                        </a>
                    </div>
                </div>
            {% elif request.user.is_authenticated %}
                <div class="navbar-item has-dropdown is-hoverable" style="color: white">
                    <a class="">
                        {{ request.user.name }}
                    </a>
                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="#">
                            Profile
                        </a>
                        <a class="navbar-item" href="#">
                            Update Profile
                        </a>
                        <a class="navbar-item" href="#">
                            Become Vendor
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="{% url 'accounts:logout' %}">
                            Logout
                        </a>
                    </div>
                </div>
            {% else %}
                <a href="{% url 'accounts:accounts' %}">
                    <i class="fa fa-user"></i>
                </a>
            {% endif %}
        </div>
    </div>
    <button id="menu-toggle" class="sm:hidden text-white focus:outline-none">
        <i class="fa fa-bars text-xl"></i>
    </button>
</nav>

markeetplace_server/templates/header/script.html
  <script>
    const menuToggle = document.getElementById('menu-toggle');
    const navLinks = document.getElementById('nav-links');

    menuToggle.addEventListener('click', () => {
      navLinks.classList.toggle('hidden');
    });


    const language = document.getElementById('language');
    const languageMenu = document.getElementById('language-dropdown');

    language.addEventListener('click', () => {
      languageMenu.classList.toggle('hidden');
    });

    const Currency = document.getElementById('currency');
    const CurrencyMenu = document.getElementById('currency-dropdown');

    Currency.addEventListener('click', () => {
      CurrencyMenu.classList.toggle('hidden');
    });

    function selectCurrency(currency) {
      document.getElementById('currency').textContent = currency;
      document.getElementById('currency-dropdown').classList.add('hidden');
    }

    function selectLanguage(language) {
      document.getElementById('language').textContent = language;
      document.getElementById('language-dropdown').classList.add('hidden');
    }
  </script>

markeetplace_server/templates/header/social_media_section.html
{% load static %}
<div class="bg-[#073741] p-2 px-4 sm:px-24 flex flex-col md:flex-row justify-centre sm:justify-between items-center text-white">
    <p class="text-sm">Welcome to Home Decor online Shopping store</p>
    <div class="flex items-center gap-3 mt-2 sm:mt-0">
      <div class="flex items-center gap-2">
        <p class="hidden sm:block">Follow us:</p>
        <i class="fa fa-twitter"></i>
        <i class="fa fa-facebook-f"></i>
        <i class="fa fa-instagram"></i>
        <i class="fa fa-youtube"></i>
        <i class="fa fa-reddit"></i>
      </div>
      <div class="h-5 w-px bg-white hidden sm:block"></div>

      <!-- Language Dropdown -->
      <div class="relative">
        <button class="flex items-center gap-2" id="language">
          <span id="language">ENG</span>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
          </svg>
        </button>
        <div id="language-dropdown" class="hidden absolute bg-white text-black rounded mt-2 shadow-lg z-10 p-7">
          <div class="flex items-centre gap-2 p-2 cursor-pointer hover:bg-gray-200" onclick="selectLanguage('ENG')">
            <img src="{% static 'assets/usimage.png' %}" alt="US Flag" class="w-5 h-5 rounded-full border">
            <p>English</p>
          </div>
          <hr>
          <div class="flex items-center gap-2 p-2 cursor-pointer hover:bg-gray-200" onclick="selectLanguage('ARB')">
            <img src="{% static 'assets/saudiflag.png' %}" alt="Saudi Flag" class="w-5 h-5 rounded-full border">
            <p>Arabic</p>
          </div>
        </div>
      </div>

      <!-- Currency Dropdown -->
      <div class="relative" >
        <button class="flex items-center gap-2" id="currency">
          <span id="currency">SR</span>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
          </svg>
        </button>
        <div id="currency-dropdown" class="hidden absolute bg-white text-black rounded mt-2 shadow-lg z-10 p-2">
          <div class="p-2 cursor-pointer hover:bg-gray-200" onclick="selectCurrency('SR')">Saudi Riyal (SR)</div>
          <hr>
          <div class="p-2 cursor-pointer hover:bg-gray-200" onclick="selectCurrency('AED')">UAE Dirham (AED)</div>
        </div>
      </div>
    </div>
  </div>